#!/bin/bash

run_brew() {
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if has "brew"; then
    echo "Updating Homebrew..."
    brew update && brew upgrade && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    brew tap daipeihust/tap

    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
      'autossh'
      'clang-format'
      'cmake'
      'colima'
      'coreutils'
      'docker'
      'docker-compose'
      'gh'
      'git'
      'glow'
      'gnupg'
      'go'
      'im-select'
      'ipmitool'
      'jq'
      'krew'
      'kubernetes-cli'
      'mdcat'
      'mosh'
      'nkf'
      'openssl'
      'pandoc'
      'python@3.14'
      'ripgrep'
      'telnet'
      'tmux'
      'tmux-xpanes'
      'uv'
      'wget'
    )

    local installed=`brew list`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew install $list_formulae && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    local -a missing_formulae=()
    local -a desired_formulae=(
      'codex'
      'font-hackgen-nerd'
      'google-chrome'
      'font-plemol-jp-nf'
      'font-ricty-diminished'
      'font-udev-gothic-nf'
      'ghostty'
      'hammerspoon'
      'iterm2'
      'cloudflare-warp'
      'karabiner-elements'
      'ollama-app'
      'tailscale-app'
      'thaw'
      'visual-studio-code'
      'zoom'
    )

    local installed=`brew list --cask`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew casks..."
      brew install --cask $list_formulae && echo "$(tput setaf 2)Installed missing casks ✔︎$(tput sgr0)"
    fi

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
    brew doctor
    echo "$(tput setaf 2)check Homebrew doctor complete. ✔︎$(tput sgr0)"

  fi
}
