#!/bin/bash

NVIM_VENV="${HOME}/.local/share/nvim-python"

run_python() {
  if has "uv"; then
    echo "Setting up neovim Python provider..."
    uv python install 3
    uv venv --python 3 "${NVIM_VENV}"
    uv pip install --python "${NVIM_VENV}/bin/python" -r ./var/requirements-nvim.txt
    echo "$(tput setaf 2)Python setup complete. ✔︎$(tput sgr0)"
  else
    echo "$(tput setaf 1)uv not found, skipping Python setup$(tput sgr0)"
  fi
}
