(source gnu)
(source melpa)

(depends-on "pallet")
(depends-on "init-loader")

;; python
(depends-on "jedi")
(depends-on "py-autopep8")

;; auto complete
(depends-on "auto-complete")
(depends-on "fuzzy")

;; highlight
(depends-on "volatile-highlights")

;; latex
(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "auto-complete-auctex")

;; dictionary
(depends-on "osx-dictionary")
(depends-on "popwin")

;; js2-mode
(depends-on "js2-mode")
(depends-on "ac-js2")




;; misc
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
